---
- hosts: all
  become: true
  tasks:
    - name: Add repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

    - name: Install git and vim
      yum:
        state: present
        name:
          - git
          - vim

    - name: Clone github repo for zabbix deployment
      git:
        repo: 'https://github.com/jordanblopez/project_auto.git'
        dest: /home/vagrant
