---
- name: 1. install the repo for zabbix
  yum:
    name: http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-1.el7.centos.noarch.rpm
    state: present

- name: 2. install zabbix server
  yum:
    state: present
    name:
      - zabbix-server-mysql
      - zabbix-web-mysql

- name: 3. copy database dump file
  copy:
    remote_src: yes
    src: /usr/share/doc/zabbix-server-mysql-3.4.3/create.sql.gz
    dest: /tmp
    mode: 644

- name: 4. import the schema
  mysql_db:
    name: zabbix
    state: import
    target: /tmp/create.sql.gz

- name: 5. edit zabbix.conf
  copy:
    src: zabbix_server.conf
    dest: /etc/zabbix/zabbix_server.conf

- name: 6. set php datetime
  lineinfile:
    path: /etc/httpd/conf.d/zabbix.conf
    regexp: '^php_value date'
    line: 'php_value date.time America/Los_Angeles'
    state: present
