---
- name: 1. install Apache
  become: true
  yum: name=httpd state=present

- name: 2. install PHP
  become: true
  yum: name=php state=present

- name: 3. start Apache
  become: true
  service: name=httpd state=started enabled=yes
